### ISSUE TITLE
[Feature]: Integration with php website

### ISSUE THREAD

**Issue by harisnaeemofficial** [JamesHawkinss/movie-web#100]
### What feature do you want to add?

Is it possible to integrate this project with PHP website?

### Why do you want to have this feature?

I want to use this project with PHP website because mostly movie websites are in PHP language and I want to get sources with this project, this is a super cool project.

**Comment by JamesHawkinss** [comment]
This request makes very little practical sense.

An example of fetching data from a php site in one of our scrapers: https://github.com/JamesHawkinss/movie-web/blob/dev/src/providers/list/gomostream/index.ts#L71

Are you asking about implementing a new scraper?

**Comment by harisnaeemofficial** [comment]
No, my question is like i have a php website and everything is scrapped by omdb/imdb/tmdb and i want to use this project to get movie playable links like you search any movie name and it gives you result. But i want these links to work with php webpage and play it on php website

**Comment by harisnaeemofficial** [comment]
Ok, Do you have any plan to create an API for movie-web in future?

**Comment by JamesHawkinss** [comment]
No
