### ISSUE TITLE
[Feature]: Sub and Dub Options 

### ISSUE THREAD

**Issue by ricemashi** [JamesHawkinss/movie-web#101]
### What feature do you want to add?

A subtitle or a dub option in the movie video player.

### Why do you want to have this feature?

It will really help more native driven users to use this web app more

**Comment by lem6ns** [comment]
the SuperStream source has subtitles, we don't have any sources currently for dubs though

**Comment by JamesHawkinss** [comment]
Unfortunately not something we can implement, if the sources provide subtitles in various languages we will implement support.
