### ISSUE TITLE
Can you self host it ?

### ISSUE THREAD

**Issue by ARR4NN** [JamesHawkinss/movie-web#12]
can i run it on my pc just to mess with it ? 
I tried starting with node . but nothing and tried live server on index.html
Could you dm me on discord, please ARR4NN#0340
Thanks

**Comment by JamesHawkinss** [comment]
Hi there, thanks for the question.

You can run it in development mode by running the following commands:
1. `yarn install`
2. `yarn start`

If you would like to build it for production (so you can live serve index.html) just run:
1. `yarn install`
2. `yarn build`
3. Serve from the built index.html

Hope this helps!

**Comment by ARR4NN** [comment]
Sick thanks mate
