### ISSUE TITLE
Nothing is working

### ISSUE THREAD

**Issue by ARR4NN** [JamesHawkinss/movie-web#14]
Neither my self-hosted or official one can find results for anything... is the method it uses not online ?

**Comment by JamesHawkinss** [comment]
The site being used is currently not reachable, nothing I can do. Will add multiple scrapers in the future, but for now we just have to wait.

**Comment by ARR4NN** [comment]
Ok thanks for the response 👍

**Comment by ARR4NN** [comment]
if i visit the site directly it does work https://lookmovie.io/api/v1/shows/search/?q=sea

**Comment by JamesHawkinss** [comment]
It's in under attack mode, so we are not able to reach it.

**Comment by ARR4NN** [comment]
ah yes i did also see that, thanks

**Comment by ARR4NN** [comment]
also while I'm here don't suppose cause you're a g you could check out my ticket 😄 #170560 
Your the best
