### ISSUE TITLE
Check this out, i added some cool things 

### ISSUE THREAD

**Issue by ARR4NN** [JamesHawkinss/movie-web#15]
https://github.com/ARR4NN/movie-web/tree/main

**Comment by JamesHawkinss** [comment]
If you wish to contribute features to this project, please create a pull request. You can find more about that here: https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

**Comment by ARR4NN** [comment]
Idk how to use pull requests lol github confuses me sometimes
