### ISSUE TITLE
Window location

### ISSUE THREAD

**Issue by ARR4NN** [JamesHawkinss/movie-web#18]
what would be the best way to impliment location hash so when you visit https://link.domain.com/#type=show?search=searchquery it will send you to the correct place

**Comment by JamesHawkinss** [comment]
I'm not sure what you mean. Can you provide an actual example URL? And explain what you're trying to achieve

**Comment by ARR4NN** [comment]
for example the link to your comment is 
https://github.com/JamesHawkinss/movie-web/issues/18**#issuecomment-884038313**
so for the movie-web you can easily navigate.
https://movie.squeezebox.dev/#type=**movie**#search=**your_search**

**Comment by JamesHawkinss** [comment]
I understand. Currently the app doesn't have this functionality, and so I haven't put any thought into how it might work. If you want to implement it yourself, please feel free.

**Comment by JamesHawkinss** [comment]
Also, I'd like to add that it's not in the spirit of open source development to copy/paste an entire repository, without forking, and to remove all credit. I would understand if you would like to make some alterations to the project for your own use, but removing all credit is not at all appreciated.

**Comment by ARR4NN** [comment]
I did fork it but I couldn't then push my changes

**Comment by ARR4NN** [comment]
So I just made a quick repo for now and it made its own readme so I will try to do the forking stuff again

**Comment by ARR4NN** [comment]
im not good at using github but i do it it a lot hmm

**Comment by JipFr** [comment]
To properly make a fork and still allow you to push, you have to properly clone the fork. I imagine you tried to download the project through the download button, but that doesn't keep the commit history and such. To clone your fork, run `git clone https://github.com/RR4NN/movie-web` after forking. Then you can make and commit changes, and you will still be able to push. 

When you want to merge back into James' repo, you can click the "create pull request" button under the contribute menu on your fork.

**Comment by ARR4NN** [comment]
this shit confusing lol

**Comment by JipFr** [comment]
Which part do you not understand?

**Comment by JamesHawkinss** [comment]
This feature has now been implemented. Example: https://movie.squeezebox.dev/#/movie/lookmovie/Hamilton/8503618-hamilton-2020
