### ISSUE TITLE
[Feature]: Attempt many sources for content to find the best

### ISSUE THREAD

**Issue by TheFlash787** [JamesHawkinss/movie-web#46]
We've run into an issue, specifically with The Walking Dead S5 E1 where it actually gave us E4 instead (E4 also gave us the same E4 episode). 

Whilst I don't think a source selector would be beneficial (as the currently selected one is usually always the best), having a small button to provide the next-best-source could be useful in the off-chance that the current recording is botched. Whilst it's a situational case, having this may prevent needing to go to another website when the only source available does break.

A 'Try Another Source' button could go here:
![image](https://user-images.githubusercontent.com/25883284/142323602-914baf40-9429-4296-8332-7035ff2cc0ce.png)

**Comment by JamesHawkinss** [comment]
We will be implementing this along with #103, so going to close this issue. Thanks for the suggestion!
