### ISSUE TITLE
Add Source Request

### ISSUE THREAD

**Issue by OshekharO** [JamesHawkinss/movie-web#58]
Hii please check this out if any of the listed scrapper api is feasible to implement in this website: [Link-Crawler](https://github.com/OshekharO/Link-Crawler)

**Comment by lem6ns** [comment]
| Definitely   | Maybe      | No        |
|--------------|------------|-----------|
| GDrivePlayer | APIMovieDB | 123Movies |
| Gomo         | DBGO       | 2Embed    |
|              | FireSonic  |           |
|              | FSAPI      |           |
|              | VidSRC     |           |
|              | SuperEmbed |           |
|              | 1MovieTV   |           |
|              | AutoEmbed  |           |
