### ISSUE TITLE
immediate mobile search results

### ISSUE THREAD

**Issue by eightyy8** [JamesHawkinss/movie-web#68]
the site on mobile only allows one key input before it gets results, but you can remove them without any problems. it needs to wait for a return.

**Comment by eightyy8** [comment]
im on ios 15.0.1

**Comment by mrjvs** [comment]
screen recording
https://cdn.discordapp.com/attachments/871713465578979351/970367660728651836/RPReplay_Final1651424065.mp4

this is most likely related to the input jumping bug, where if you type anywhere thats not the end of the input text. it will jump to the end of the string

**Comment by mrjvs** [comment]
after some more research:
 - it's not because of jumping input, that has been fixed
 - it is not because of being a controlled input
 - I suspect its because it's linked to the url, it may be triggering a rerender of the input multiple times
