### ISSUE TITLE
does not work well superstream

### ISSUE THREAD

**Issue by madrid2022ok** [JamesHawkinss/movie-web#95]
![Screenshot_20221205-221339_Chrome](https://user-images.githubusercontent.com/105641464/205744009-ff85023f-d050-48af-8915-786f447039f7.jpg)

I can't play the series and movies I get this message in provider superstream in movie-web

**Comment by lem6ns** [comment]
Resolved by #93.

**Comment by madrid2022ok** [comment]
ok friend
